### ISSUE TITLE
Unit Test -- GitHub Actions/ Pytest verification

### ISSUE THREAD

**Issue by rexdivakar** [rexdivakar/Notifly#24]
## Script Title -

**what will change** -

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

#### Sanchit -- Discord id (sanchit#5988)

Discord server  - https://discord.gg/e47wmTW

Happy Coding,

**Comment by Yagueteiro** [comment]
What do you need in this issue?

**Comment by rexdivakar** [comment]
Hey @Yagueteiro, Sorry but we have already fixed this issue, Anyways thanks for checking in.
