### ISSUE TITLE
Connectivity Bug

### ISSUE THREAD

**Issue by rexdivakar** [rexdivakar/Notifly#31]
There is no exception to handle the connectivity drop crash

![image](https://user-images.githubusercontent.com/15235122/99342943-f7b42480-28b2-11eb-9da1-5540d3dd1bab.png)

**Comment by zeel-codder** [comment]
such a cool package man 🔥. I want to work on this issue. can you tell me more about this bug?
Thank you.

**Comment by rexdivakar** [comment]
Hey @zeel-codder thanks for your interest ✌ this issue occurs during the file transmission phase when the connection drops using telegram as a notification mode. Feel free to dig in and let me know in case you need help. Happy Collaborating 😉

**Comment by zeel-codder** [comment]
hi, I set up the project local and pay around the code. you can find I also create one pull request for change in the README.md file.
pull request:#63
I send the message as well as files by running the code. but still, I am not getting this error. 
can you tell me more about this error in which senior this will happend?

**Comment by rexdivakar** [comment]
Well, the issue is in case of network lag or connectivity problem this failure occurs I'm curious to find a workaround to fix this !!

**Comment by zeel-codder** [comment]
Humm, I am working on it too.  Like, hear we have to just handle the error and catch it right.

**Comment by rexdivakar** [comment]
yup u got it
