### ISSUE TITLE
Alternative of copy pasting the bot api token

### ISSUE THREAD

**Issue by aakash-cse** [rexdivakar/Notifly#36]
Why can't we create a new ".env" file and use the file to fetch the token so that the token won't be visible in the code??

**Comment by SanchitJain123** [comment]
Hi @aakash-cse, are you referring to the token specified in the test file or in general we should provide a functionality for the users to use .env file for setting token?

**Comment by aakash-cse** [comment]
> Hi @aakash-cse, are you referring to the token specified in the test file or in general we should provide a functionality for the users to use .env file for setting token?

Yes

**Comment by SanchitJain123** [comment]
are you working on this @aakash-cse ?

**Comment by aakash-cse** [comment]
> are you working on this @aakash-cse ?

Yes I will create pull request tomorrow

**Comment by SanchitJain123** [comment]
#38
