### ISSUE TITLE
DOCUMENTATION 

### ISSUE THREAD

**Issue by akrish4** [rexdivakar/Notifly#37]
Hi @chmey @rexdivakar 
I would like to contribute this repository
If there is any kind of documentation needed for this project do let me now 
I would be glad to work on it.

**Comment by rexdivakar** [comment]
Hey @akrish4  we already have documented the process, may be you can look into writing up use cases of monitoring the AI model training and raise a PR on that.

**Comment by akrish4** [comment]
> Hey @akrish4 we already have documented the process, may be you can look into writing up use cases of monitoring the AI model training and raise a PR on that.

@rexdivakar  Is there any other things to be documented ? Kindly let me know , This I am not understanding.

**Comment by rexdivakar** [comment]
The key idea of our work is to monitor and track the metrics of the models during training on Tensorflow Framework, It would be great if u can document the process work flow of that @akrish4 

Please clone the repo and run the test.py file to check how it works.

**Comment by rexdivakar** [comment]
Are you working on it ? @akrish4

**Comment by akrish4** [comment]
> Are you working on it ? @akrish4

Actually I am not able work in this since I didnt understand it

**Comment by rexdivakar** [comment]
please ping me over discord @root#5998

**Comment by rexdivakar** [comment]
Are u still interested in taking up this task ? @akrish4

**Comment by rexdivakar** [comment]
Closing the issue due to no response from the user
