### ISSUE TITLE
Integrate Welcome bot

### ISSUE THREAD

**Issue by muthuannamalai12** [rexdivakar/Notifly#39]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC.

**Comment by rexdivakar** [comment]
Sure go ahead. Please do add the below details to the template,


🌟 Star it 🍴Fork it 🤝 Contribute to it!

Discord server - https://discord.gg/tTJQxvSaDP

Happy Coding,

**Comment by muthuannamalai12** [comment]
I have created a pull request. Kindly review it

**Comment by muthuannamalai12** [comment]
@rexdivakar Can you please add DWOC label here also
