### ISSUE TITLE
Creation of issue template

### ISSUE THREAD

**Issue by Sloth-Panda** [rexdivakar/Notifly#41]
There is no issue template so can add one let me know

**Comment by rexdivakar** [comment]
go ahead add them @Sloth-Panda

**Comment by Sloth-Panda** [comment]
Can you also add dwoc and level tag

**Comment by Sloth-Panda** [comment]
Kindly add a level-2/1 tag to it otherwise it won't be counted under DWOC

**Comment by rexdivakar** [comment]
Thanks for ur contribution
