### ISSUE TITLE
Readme updation

### ISSUE THREAD

**Issue by Sloth-Panda** [rexdivakar/Notifly#42]
Readme can be updated by adding gifs, adding open-source programs this project is  a part of section and also by improving badges

Let me know if this needs to be done

**Comment by rexdivakar** [comment]
Can u please show some example ?? @Sloth-Panda

**Comment by Sloth-Panda** [comment]
Like anything that will be nicer and will  link to a keyword those gifs may be added and badges like how many contributors and others too

**Comment by rexdivakar** [comment]
Hey @SanchitJain123 what do u say?

**Comment by SanchitJain123** [comment]
Yes i agree adding gifs would be much cooler in terms of presentation, documentation will look more good.

**Comment by rexdivakar** [comment]
Cool then go ahead @Sloth-Panda

**Comment by Sloth-Panda** [comment]
@rexdivakar  also please attach a level-1/2 tag to it else these are not counted
