### ISSUE TITLE
Duplicate data in readme, code_of_conduct, and contributing file

### ISSUE THREAD

**Issue by Sloth-Panda** [rexdivakar/Notifly#46]
Some code_of_conduct content is in contributing file and some contributing content is in readme which is not necessarily required
and unnecessarily creates duplicate

**Comment by Sloth-Panda** [comment]
Let me know if this needs to be resolved

**Comment by rexdivakar** [comment]
It's ok we shall manage it, thanks for your help @Sloth-Panda
