### ISSUE TITLE
Add Contributors Table in README.md File

### ISSUE THREAD

**Issue by samir-0711** [rexdivakar/Notifly#51]
## 📚 Documentation

Like this
![image](https://user-images.githubusercontent.com/68433936/104680910-02563300-5717-11eb-86d4-609899413555.png)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/rexdivakar/Notifly/blob/main/CONTRIBUTING.md)?

Yes

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by rexdivakar** [comment]
Is that automated or do u want us to manually add them to the json files ? @samir-0711

**Comment by samir-0711** [comment]
Automated

**Comment by rexdivakar** [comment]
I think we are won't be going forward with this feature, for now, Anyways thanks for checking by @samir-0711
