### ISSUE TITLE
Adding Wiki Pages

### ISSUE THREAD

**Issue by rexdivakar** [rexdivakar/Notifly#53]
## 📚 Documentation

(A clear and concise description of what the issue is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/rexdivakar/Notifly/blob/main/CONTRIBUTING.md)?

(Write your answer here.)

**Comment by Sloth-Panda** [comment]
Hey, can I do this?

**Comment by rexdivakar** [comment]
Sure, but I require a precise well-documented workflow of the package

**Comment by Sloth-Panda** [comment]
What different should i do as compared to readme or same as readme??

**Comment by rexdivakar** [comment]
I need a complete workflow of the package to be covered like,
What it does?
how it tracks?
how to send messages from the package and more.

**Comment by rexdivakar** [comment]
Are u still working on this issue ? @Sloth-Panda

**Comment by vismitap** [comment]
Hey! May I work on this issue??

**Comment by rexdivakar** [comment]
Cool assigning it to you @vismitap  Please create a detailed wiki doc and ping me if u require anything else.

**Comment by vismitap** [comment]
> Cool assigning it to you @vismitap Please create a detailed wiki doc and ping me if u require anything else.

Hey! I wanted to ask you certain questions:
* How many pages do I need to create for the wiki?
* Can you suggest the title of the pages so I get an idea of what content you would like to have on the wiki?
* Is there any content doc already that you have made which I need to follow? Or can I write my own content?
* If there are multiple pages, should I be raising an issue per page  as multiple pages will have quite detailed content and an issue dedicated to a page will be easy for both of us to work on? 😅

**Comment by rexdivakar** [comment]
The content we expect is just a user guide of how the package works, you can refer to README.md in the repo for basic steps apart from that please install the package and try it then give your workflow ideas on this! 
Page count doesn't matter as long as u capture the key functionalities of the package.
I just don't want to clutter it keep it simple and clean.

**Comment by vismitap** [comment]
> The content we expect is just a user guide of how the package works, you can refer to README.md in the repo for basic steps apart from that please install the package and try it then give your workflow ideas on this!
> Page count doesn't matter as long as u capture the key functionalities of the package.
> I just don't want to clutter it keep it simple and clean.

Hey! Check this out https://github.com/vismitap/Notifly/wiki 😄

**Comment by rexdivakar** [comment]
Hey @vismitap its looks great could u please add few more details about **TensorFlow Integration with Notifly**  like the output of the trigger and the how to use it during the function call !! in case of any doubts please reach out to me on discord @root#5998

**Comment by vismitap** [comment]
> Hey @vismitap its looks great could u please add few more details about **TensorFlow Integration with Notifly** like the output of the trigger and the how to use it during the function call !! in case of any doubts please reach out to me on discord @root#5998

okie sure!👍

**Comment by vismitap** [comment]
> Hey @vismitap its looks great could u please add few more details about **TensorFlow Integration with Notifly** like the output of the trigger and the how to use it during the function call !! in case of any doubts please reach out to me on discord @root#5998

Hey, I had contacted you on discord. Please guide me with TensorFlow integration so that I can complete this task 😅

**Comment by rexdivakar** [comment]
https://discord.gg/YzYHDKrt

**Comment by vismitap** [comment]
> https://discord.gg/YzYHDKrt

I do not have the permission to type in any of the 3 channels.

**Comment by vismitap** [comment]
> https://discord.gg/YzYHDKrt
> 
> I'm the admin pls ping me

Ok👍👍

**Comment by rexdivakar** [comment]
Thanks for ur awesome work @vismitap  😊👍
