### ISSUE TITLE
Contribution Table

### ISSUE THREAD

**Issue by Dhriti-Roy** [rexdivakar/Notifly#57]
Adding Contribution Table .

**Comment by Dhriti-Roy** [comment]
I want to work on this issue, kindly assign this to me.

**Comment by rexdivakar** [comment]
Hey @Dhriti-Roy currently we are not looking for any non-coding updates to the repo. If interested pls check out other issues and try to work on them.

**Comment by Dhriti-Roy** [comment]
Okay, no problem.
