### ISSUE TITLE
Add contributor's table 

### ISSUE THREAD

**Issue by himanshu007-creator** [rexdivakar/Notifly#58]
## 📚 Documentation

There is need of a contributor's table in readme

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/rexdivakar/Notifly/blob/main/CONTRIBUTING.md)?

Yes

**Comment by rexdivakar** [comment]
Sorry, @himanshu007-creator  we don't need a contributor's table for now !! We do appreciate ur interest Thanks for your check-in
