### ISSUE TITLE
Change the documentation page.

### ISSUE THREAD

**Issue by zeel-codder** [rexdivakar/Notifly#64]
## 📚 Documentation
zeel, hear. in online python documentation of this project. I find the same method issue like (#63).

![Screenshot from 2021-09-10 11-27-54](https://user-images.githubusercontent.com/69882648/132807375-9ea3b39e-c51c-4f07-84dc-2bc9929c2557.png)

**Comment by rexdivakar** [comment]
Oh yes, it's been a while ever since we updated our changes will fix them up and release the changes soon

**Comment by soma2000-lang** [comment]
Can I work on this issue?

**Comment by rexdivakar** [comment]
yeah please go ahead

**Comment by eeshvardasikcm** [comment]
This screenshot is a great start to documentation. I can see how I could going with this. Looking forward to the updates.

Great to have some telegram connection. Exciting Notifly advertisment showed up on my device. I don't have a linux vm active at the moment. The advertisement alone has convinced me to choose Notifly for some of my upcoming notification needs

**Comment by rexdivakar** [comment]
Hey @soma2000-lang any updates so far ?

**Comment by soma2000-lang** [comment]
@rexdivakar In the readme file, I can see the send_document part has already been changed to send_file. What else changes can I do here??

**Comment by rexdivakar** [comment]
thats it please make a PR once your done, apologies for the delayed response !
