### ISSUE TITLE
Feature to get message from telegram

### ISSUE THREAD

**Issue by rexdivakar** [rexdivakar/Notifly#7]
Use telegram api to receive message

**Comment by bayucakra20** [comment]
Hi, I'd would like to work on this issue

**Comment by rexdivakar** [comment]
The idea is to add a method to retrieve messages sent from the chat and store it locally 

Issue assigned to @bayucakra20 
🌟 Star it 🍴Fork it 🤝 Contribute to it!
Happy Coding..

Feel free to drop in https://discord.gg/e47wmTW

**Comment by bayucakra20** [comment]
> The idea is to add a method to retrieve messages sent from the chat and store it locally
> 
> Issue assigned to @bayucakra20
> 🌟 Star it 🍴Fork it 🤝 Contribute to it!
> Happy Coding..
> 
> Feel free to drop in https://discord.gg/e47wmTW

Hi @rexdivakar , for receiving messages of chatbot, actually i can use from `getUpdates` api which currently method is already there and I can use it, is it enough to use that? or should I use other api like `getMessages` ? and for storing data locally, I would like to store it in csv file, or do you have any suggestion? thank you

**Comment by rexdivakar** [comment]
hey @bayucakra20  yes u can use _getUpdates_  and please store the data (chat details, user details) in a json format for easier use in future.

**Comment by bayucakra20** [comment]
I see, okay will use json format then, thank you @rexdivakar for the suggestion
